[package]
name = "leafhub-config"
version = "0.1.0"
edition = "2024"

[dependencies]
erased-serde = "0.4.6"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
serde_yml = "0.0.12"
toml = "0.8.20"
